name = "TypedMatrices"
uuid = "a0429a07-0388-4c37-a18a-23d110f8915c"
authors = ["Andy Zhang <37402126+AnzhiZhang@users.noreply.github.com> and contributors"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Polynomials = "4"
julia = "1.6.7"
